# -*- coding: utf-8 -*-
"""Wanderchat v0.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRL0WNPjkPdHZdE-u8joj8G7Pan4ejVO
"""

!pip install -q faiss-cpu pdfplumber python-docx tavily

import faiss
import numpy as np
import pdfplumber
from docx import Document
from sentence_transformers import SentenceTransformer
import ipywidgets as widgets
from IPython.display import display, clear_output


embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50


# ── Text Extraction ───────────────────────────────────────────────────────────

def extract_pdf(file_path):
    text = ""
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text


def extract_docx(file_path):
    doc = Document(file_path)
    return "\n".join([para.text for para in doc.paragraphs if para.text.strip()])


def extract_text(file_path):
    if file_path.endswith(".pdf"):
        return extract_pdf(file_path)
    elif file_path.endswith(".docx") or file_path.endswith(".doc"):
        return extract_docx(file_path)


# ── Chunking ──────────────────────────────────────────────────────────────────

def chunk_text(text):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = start + CHUNK_SIZE
        chunk = " ".join(words[start:end])
        chunks.append(chunk)
        start += CHUNK_SIZE - CHUNK_OVERLAP
    return chunks


# ── FAISS Index ───────────────────────────────────────────────────────────────

faiss_index = None
chunk_store = []


def build_index(file_paths):
    global faiss_index, chunk_store

    all_chunks = []
    for fp in file_paths:
        text = extract_text(fp)
        chunks = chunk_text(text)
        all_chunks.extend(chunks)

    chunk_store = all_chunks
    embeddings = embedding_model.encode(all_chunks, show_progress_bar=True)
    embeddings = np.array(embeddings).astype("float32")

    dim = embeddings.shape[1]
    faiss_index = faiss.IndexFlatL2(dim)
    faiss_index.add(embeddings)

    print(f"Index built with {len(all_chunks)} chunks from {len(file_paths)} files.")


def retrieve(query, top_k=5):
    query_embedding = embedding_model.encode([query])
    query_embedding = np.array(query_embedding).astype("float32")

    distances, indices = faiss_index.search(query_embedding, top_k)
    results = [chunk_store[i] for i in indices[0] if i < len(chunk_store)]
    return "\n\n".join(results)

build_index(["Thiruvananthapuram-E-Brochure.pdf", "alappuzhahrj28.pdf", "ernakulam.pdf", "munnar-e-brochure.pdf"])

conversation_history = []

def add_to_memory(user_input, agent_response):
    conversation_history.append({"user": user_input, "agent": agent_response})
    if len(conversation_history) > 5:
        conversation_history.pop(0)

def format_history():
    if not conversation_history:
        return "No previous conversation."
    history = ""
    for turn in conversation_history:
        history += f"User: {turn['user']}\nAgent: {turn['agent']}\n\n"
    return history.strip()

MOA_LAYER1_PROMPT_WITH_MEMORY = """You are a knowledgeable Kerala tourism assistant.

Conversation History:
{conversation_history}

Retrieved Context:
{retrieved_context}

User Query:
{user_query}

Give a detailed and informative response covering what you know about this topic."""

MOA_LAYER2_PROMPT = """You are a Kerala tourism expert refining and improving responses.

You are given 3 responses from other assistants for the same user query. Collect the best points from all 3, remove redundancy, fix inaccuracies, and give an improved response.

User Query:
{user_query}

Response 1:
{response_1}

Response 2:
{response_2}

Response 3:
{response_3}

Give a single improved response that combines the best of all three."""


MOA_LAYER3_PROMPT = """You are a Kerala tourism expert. Your job is to synthesize 3 refined responses into one single, coherent, final response.

User Query:
{user_query}

Refined Response 1:
{response_1}

Refined Response 2:
{response_2}

Refined Response 3:
{response_3}

Combine these into one clear, complete, and well-structured final response. Do not add new information. Only synthesize what is already there."""


WEB_SURFER_PROMPT = """You are analyzing a tourism-related response to identify what real-time or recent information is missing or could be outdated.

User Query:
{user_query}

LLM Response:
{llm_response}

Your tasks:
1. Identify key entities in the query and response: places, landmarks, activities, food, events, etc.
2. Identify what information is likely outdated or missing: weather, traffic, restaurant recommendations, entry fees, events, timings, current conditions.
3. Generate specific search queries to fill those gaps.

Output a JSON object in this exact format:
{{
  "entities": {{"places": [], "activities": [], "food": [], "other": []}},
  "missing_or_outdated": [],
  "search_queries": []
}}

Only output the JSON. Nothing else."""


REASONING_PROMPT = """You are a verification expert for a Kerala tourism assistant.

Your job is to check if the web search results cover the missing or outdated information that was identified, and then produce a final merged response.

User Query:
{user_query}

Original LLM Response:
{llm_response}

Missing/Outdated Information That Was Searched For:
{missing_info}

Web Search Results:
{web_results}

Tasks:
1. Check if the web search results address the missing or outdated information.
2. If YES: merge the LLM response and web search results into one complete response. Output:
{{
  "status": "pass",
  "final_response": "<merged response here>"
}}
3. If NO (web results are insufficient or irrelevant): Output:
{{
  "status": "retry",
  "missing_still": "<what is still missing>"
}}

Only output the JSON. Nothing else."""


FORMATTER_PROMPT = """You are a data formatter for a Kerala tourism assistant.

You will receive a final response about a Kerala tourism topic. Your job is to extract and present only the structured factual data from it.

Final Response:
{final_response}

Extract any structured facts that are present (only include fields that actually exist in the response):
- Distances (e.g., from X to Y: Z km)
- Opening time
- Closing time
- Entry fees
- Best time to visit
- Restaurants / food recommendations
- Weather / current conditions
- Traffic conditions
- Events / festivals

Present them in a clean structured format. For any narrative or descriptive information (history, cultural significance, etc.), keep it as a short paragraph under "About".

Do not add any information that is not in the response."""


FORMAT_EVALUATOR_PROMPT = """You are a format quality checker for a Kerala tourism assistant.

You will receive the original data that was sent to the formatter, the formatter's output, and you need to verify if the structured output is correct and complete.

Original Data:
{original_data}

Formatter Output:
{formatter_output}

Check for:
1. Any factual data present in the original that is missing from the formatted output.
2. Any data that was incorrectly formatted or misrepresented.
3. Any fields that are empty but shouldn't be, or fields with wrong values.

If everything is correct, output:
{{
  "status": "pass"
}}

If there are issues, output:
{{
  "status": "fail",
  "issues": "<describe what is wrong>",
  "fix": "<describe exactly what needs to be fixed>"
}}

Only output the JSON. Nothing else."""

def run_pipeline(user_query):
    retrieved_context = retrieve(user_query)
    moa_response = run_moa(user_query, retrieved_context)
    evaluated_response = run_evaluator(user_query, moa_response)
    final_response = run_formatter(evaluated_response)
    add_to_memory(user_query, final_response)
    return final_response

from openai import OpenAI
from tavily import TavilyClient
import json
from IPython.display import clear_output, display

OPENROUTER_API_KEY = "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"
TAVILY_API_KEY = "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"

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)
tavily_client = TavilyClient(api_key=TAVILY_API_KEY)

MOA_MODEL_1 = "arcee-ai/trinity-mini:free"
MOA_MODEL_2 = "nvidia/nemotron-3-nano-30b-a3b:free"
MOA_MODEL_3 = "arcee-ai/trinity-large-preview:free"
MOA_LAYER3_MODEL = "liquid/lfm-2.5-1.2b-thinking:free"
WEB_QUERY_MODEL = "arcee-ai/trinity-mini:free"
REASONING_MODEL = "nvidia/nemotron-3-nano-30b-a3b:free"
FORMATTER_MODEL = "liquid/lfm-2.5-1.2b-thinking:free"
FORMAT_EVALUATOR_MODEL = "liquid/lfm-2.5-1.2b-instruct:free"

def llm_request(model, system_prompt, user_prompt):
    print(f"[llm_request] calling model={model}")
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    content = response.choices[0].message.content
    print(f"[llm_request] received model={model} len={len(content)}")
    return content

def run_moa(user_query, retrieved_context):
    print("[run_moa] start")
    history = format_history()
    l1_prompt = MOA_LAYER1_PROMPT_WITH_MEMORY.format(
        conversation_history=history,
        retrieved_context=retrieved_context,
        user_query=user_query
    )
    print("[run_moa] layer1 requests")
    l1_r1 = llm_request(MOA_MODEL_1, "You are a helpful Kerala tourism assistant.", l1_prompt)
    print(f"[run_moa] l1_r1 len={len(l1_r1)}")
    l1_r2 = llm_request(MOA_MODEL_2, "You are a helpful Kerala tourism assistant.", l1_prompt)
    print(f"[run_moa] l1_r2 len={len(l1_r2)}")
    l1_r3 = llm_request(MOA_MODEL_3, "You are a helpful Kerala tourism assistant.", l1_prompt)
    print(f"[run_moa] l1_r3 len={len(l1_r3)}")
    l2_prompt = MOA_LAYER2_PROMPT.format(user_query=user_query, response_1=l1_r1, response_2=l1_r2, response_3=l1_r3)
    print("[run_moa] layer2 requests")
    l2_r1 = llm_request(MOA_MODEL_1, "You are a Kerala tourism expert.", l2_prompt)
    print(f"[run_moa] l2_r1 len={len(l2_r1)}")
    l2_r2 = llm_request(MOA_MODEL_2, "You are a Kerala tourism expert.", l2_prompt)
    print(f"[run_moa] l2_r2 len={len(l2_r2)}")
    l2_r3 = llm_request(MOA_MODEL_3, "You are a Kerala tourism expert.", l2_prompt)
    print(f"[run_moa] l2_r3 len={len(l2_r3)}")
    l3_prompt = MOA_LAYER3_PROMPT.format(user_query=user_query, response_1=l2_r1, response_2=l2_r2, response_3=l2_r3)
    print("[run_moa] layer3 request")
    final = llm_request(MOA_LAYER3_MODEL, "You are a Kerala tourism expert.", l3_prompt)
    print(f"[run_moa] finished len={len(final)}")
    return final

def build_and_search(user_query, llm_response):
    print("[build_and_search] building queries")
    raw = llm_request(
        WEB_QUERY_MODEL,
        "You are a web search query builder for a Kerala tourism assistant.",
        WEB_SURFER_PROMPT.format(user_query=user_query, llm_response=llm_response)
    )
    print(f"[build_and_search] raw query builder len={len(raw)}")
    parsed = json.loads(raw)
    queries = parsed["search_queries"]
    missing_info = parsed.get("missing_or_outdated", None)
    web_data = []
    for i, q in enumerate(queries):
        print(f"[build_and_search] searching query {i+1}/{len(queries)}: {q}")
        results = tavily_client.search(q, max_results=3)
        web_data.extend(results.get("results", []))
        print(f"[build_and_search] got {len(results.get('results', []))} results for query {i+1}")
    print(f"[build_and_search] total web results={len(web_data)} missing_info={bool(missing_info)}")
    return missing_info, web_data

def run_evaluator(user_query, llm_response):
    print("[run_evaluator] start")
    missing_info, web_data = build_and_search(user_query, llm_response)
    print("[run_evaluator] running reasoning model first pass")
    raw = llm_request(
        REASONING_MODEL,
        "You are a verification expert for a Kerala tourism assistant.",
        REASONING_PROMPT.format(
            user_query=user_query,
            llm_response=llm_response,
            missing_info=missing_info,
            web_results=web_data
        )
    )
    print(f"[run_evaluator] reasoning raw len={len(raw)}")
    parsed = json.loads(raw)
    if parsed.get("status") == "pass":
        print("[run_evaluator] status=pass")
        return parsed["final_response"]
    else:
        print("[run_evaluator] status!=pass retrying once")
        missing_info, web_data = build_and_search(user_query, llm_response)
        raw = llm_request(
            REASONING_MODEL,
            "You are a verification expert for a Kerala tourism assistant.",
            REASONING_PROMPT.format(
                user_query=user_query,
                llm_response=llm_response,
                missing_info=parsed.get("missing_still"),
                web_results=web_data
            )
        )
        print(f"[run_evaluator] reasoning retry raw len={len(raw)}")
        parsed = json.loads(raw)
        print("[run_evaluator] retry finished")
        return parsed["final_response"]

def run_formatter(final_response):
    print("[run_formatter] start")
    formatted = llm_request(
        FORMATTER_MODEL,
        "You are a data formatter for a Kerala tourism assistant.",
        FORMATTER_PROMPT.format(final_response=final_response)
    )
    print(f"[run_formatter] formatted len={len(formatted)} running evaluator")
    eval_raw = llm_request(
        FORMAT_EVALUATOR_MODEL,
        "You are a format quality checker for a Kerala tourism assistant.",
        FORMAT_EVALUATOR_PROMPT.format(original_data=final_response, formatter_output=formatted)
    )
    print(f"[run_formatter] eval raw len={len(eval_raw)}")
    eval_parsed = json.loads(eval_raw)
    if eval_parsed.get("status") == "pass":
        print("[run_formatter] format status=pass")
        return formatted
    else:
        print("[run_formatter] format status!=pass fixing")
        fixed = llm_request(
            FORMATTER_MODEL,
            "You are a data formatter for a Kerala tourism assistant.",
            FORMATTER_PROMPT.format(final_response=final_response) +
            f"\n\nPrevious output had issues: {eval_parsed.get('issues')}\nFix: {eval_parsed.get('fix')}\n\nPrevious wrong output:\n{formatted}"
        )
        print("[run_formatter] fixed output generated")
        return fixed

def run_pipeline(user_query):
    print("[run_pipeline] start")
    print("[run_pipeline] retrieving context")
    retrieved_context = retrieve(user_query)
    print(f"[run_pipeline] retrieved_context type={type(retrieved_context)}")
    print("[run_pipeline] running MoA")
    moa_response = run_moa(user_query, retrieved_context)
    print(f"[run_pipeline] moa_response len={len(moa_response)}")
    print("[run_pipeline] running evaluator")
    evaluated_response = run_evaluator(user_query, moa_response)
    print(f"[run_pipeline] evaluated_response len={len(evaluated_response)}")
    print("[run_pipeline] running formatter")
    final_response = run_formatter(evaluated_response)
    print(f"[run_pipeline] final_response len={len(final_response)}")
    print("[run_pipeline] adding to memory")
    add_to_memory(user_query, final_response)
    print("[run_pipeline] finished")
    return final_response

chat_output = widgets.Output()
user_input = widgets.Text(
    placeholder="Ask about Kerala tourism...",
    layout=widgets.Layout(width="70%")
)
send_button = widgets.Button(
    description="Send",
    button_style="primary",
    layout=widgets.Layout(width="10%")
)

def on_send(b):
    query = user_input.value.strip()
    if not query:
        return
    user_input.value = ""
    with chat_output:
        print(f"You: {query}")
        print("Agent: pipeline starting...")
        response = run_pipeline(query)
        # clear_output(wait=True)
        print(f"You: {query}\n")
        print(f"Agent:\n{response}")
        print("-" * 60)

send_button.on_click(on_send)

display(widgets.HBox([user_input, send_button]))
display(chat_output)

"""You: list all the tourists spots in ernakulam

Agent:
- Fort Kochi Heritage Zone: Rs 20 (adults), entry fee Rs 10 (children), 9am-6pm daily.
- Hill Palace Museum: Inr. 30 (adults), 9am-5pm, closed Tuesdays.
- Dutch Palace: Inr. 5, 9am-5pm.
- Kerala Folklore Museum: Inr. 20, 9am-5pm.
- Marine Drive & Ernakulam–Kochi Bridge: Free, 24hr access.
- Kerari Temple & Bird Sanctuary: Free, open 6am-7pm.
- Paradesi Synagogue & Jew Town: Free, 9am-5pm.
- Weather: 30.2°C heat, feels like 34°C, mist, 70% humidity.
- Traffic: 54.5% congestion, moderate-high volume, 0 major incidents.
- Upcoming Events: Athachamayam Festival 2023, Feast of Our Lady of Ransom 2026, Ayilyam Festival in February.
- Practical Tips: Use UPI, wear shoes, peak season Oct-Mar.

Test 1

You: give me a list of toruist spots in ernakulam

Agent:
- Entry fees: Free
- Current weather: 30.1°C, 62% humidity, gentle winds
- Best time to visit: October-March
- Traffic condition: Vehicle entry restricted after 4 PM; ferries suspended after 7 PM
- Restaurants: Mosaic, Kochi Kapital Kafe, etc.
- Events: Annayinga Festival, Kochi Muziris Biennale
- Backwater cruises: $165, village punt boats at $31.15
- Transportation: Kochi Metro operating 6 AM–10 PM
------------------------------------------------------------

Test 2

You: pick the best go to torist spot in munnar with it's description and give me detailes related to entry fee, food spots, etc.

Agent:
Opening time: 8:00 am
Closing time: 2:00 pm
Entry fees: ₹95, ₹500, ₹40
Restaurants: Hotel Eastend Munnar, Issac’s Residency, etc.
Weather: Clear skies, 22°C
Traffic: Traffic congestion on Neriamangalam-Munnar stretch
Events/Festivals: None explicitly stated.
------------------------------------------------------------

## limitations

1. dataset
+ karnataka
2. search
+ live updating toursit sites
3. response structure

- insufficent dataset vector db

- which vector store to use if file size very high
- web search accuracy (from which site is the data getting collect?, is it relieble?)

build comparison betwwen each process - multiple models
"""